apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coscup-app-ingress
spec:
  rules:
  - host: {{ .Values.app.url.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coscup-app-svc
            port:
              name: http